In [1]:
import pandas as pd
import altair as alt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

In [2]:
df = pd.read_csv("base_carrera_musical_3.csv", delimiter=";", encoding="UTF-8")
df.head(200)

,album_id,artista_proyecto,tipo_discografia,nombre_album,año_lanzamiento,UK_peak,semanas_chart_UK,US_peak,semanas_chart_US,certificacion_BPI
0,BLU_001,Blur,Album,Leisure,1991,7,22,-,-,Oro
1,BLU_002,Blur,Album,Modern Life Is Rubbish,1993,15,19,-,-,Oro
2,OAS_001,Oasis,Album,Definitely Maybe,1994,1,663,13,22,10xPlatino
3,OAS_002,Oasis,Live album,1994-04-24: Glastonbury Festival of Contempora...,1994,-,-,-,-,NaN
4,OAS_003,Oasis,Live broadcast,Oasis - Evening Session 1993,1994,-,-,-,-,NaN
5,BLU_003,Blur,Album,Parklife,1994,1,120,-,-,4xPlatino
6,BLU_004,Blur,Compilation,The Special Collectors Edition,1994,-,-,43,1,NaN
7,OAS_004,Oasis,Album,(What's the Story) Morning Glory?,1995,1,767,4,81,19xPlatino
8,OAS_005,Oasis,Live album,Live by the Sea,1995,-,-,-,-,3xPlatino
9,BLU_005,Blur,Album,The Great Escape,1995,1,56,150,1,3xPlatino
10,OAS_006,Oasis,Live album,… There and Then,1996,-,-,-,-,8xPlatino
11,BLU_006,Blur,Live album,Live at the Budokan,1996,77,1,-,-,NaN
12,BLU_007,Blur,Live album,Planet Live!,1996,-,-,-,-,NaN
13,OAS_007,Oasis,Album,Be Here Now,1997,1,51,2,26,7xPlatino
14,OAS_008,Oasis,Spokenword album,Brothers: From childhood to Oasis Real Story,1997,-,-,-,-,NaN
15,BLU_008,Blur,Album,Blur,1997,1,75,61,37,Platino
16,BLU_009,Blur,Live album,Live,1997,-,-,-,-,NaN
17,OAS_009,Oasis,Compilation,The Masterplan,1998,2,45,51,2,3xPlatino
18,BLU_010,Blur,Live remix album,Bustin' + Dronin',1998,100,1,56,1,NaN
19,BLU_011,Blur,Album,13,1999,1,NaN,80,5,Platino
20,BLU_012,Blur,Compilation,10 Year Anniversary Box Set,1999,-,-,-,-,NaN
21,DAM_001,Damon Albarn & Michael Nyman,Soundtrack album,Ravenous,1999,-,-,-,-,NaN
22,OAS_010,Oasis,Album,Standing on the Shoulder of Giants,2000,1,36,24,8,2xPlatino
23,OAS_011,Oasis,Live album,Familiar to Millions,2000,5,13,182,1,Platino
24,BLU_013,Blur,Compilation,Blur: The Best Of,2000,3,62,186,1,NaN
25,GOR_001,Gorillaz,EP,Tomorrow Comes Today,2000,-,-,-,-,NaN
26,BLU_014,Blur,EP,B-Sides Gig EP,2001,-,-,-,-,NaN
27,GOR_002,Gorillaz,Album,Gorillaz,2001,3,82,14,45,3xPlatino
28,GOR_003,Gorillaz,Compilation,G Sides,2001,65,1,11,5,Plata
29,DAM_002,Damon Albarn & Einar Örn Benediktsson,Soundtrack album,101 Reykjavík,2001,-,-,-,-,NaN
30,OAS_012,Oasis,Album,Heathen Chemistry,2002,1,50,23,5,4xPlatino
31,DAM_003,Afel Bocoum /Damon Albarn/Toumani Diabaté/Ko K...,Album,Mali Music,2002,81,1,-,-,NaN
32,GOR_004,Spacemonkeyz vs. Gorillaz,Remix album,Laika Come Home,2002,-,-,156,1,NaN
33,BLU_015,Blur,Album,Think Tank,2003,1,14,56,3,Oro
34,DAM_004,Damon Albarn,Album,Democrazy,2003,-,-,-,-,NaN
35,BLU_016,Blur,Documentary compilation,Starshaped,2004,-,-,-,-,NaN
36,OAS_013,Oasis,Album,Don't Believe the Truth,2005,1,41,12,7,3xPlatino
37,OAS_014,Oasis,Live album,2005-06-20: UIC Pavilion Chicago IL USA,2005,-,-,-,-,NaN
38,GOR_005,Gorillaz,Album,Demon Days,2005,1,79,6,88,6xPlatino
39,OAS_015,Oasis,Compilation,Stop the Clocks,2006,2,74,89,2,5xPlatino
40,OAS_016,Oasis,EP,Stop the Clocks EP,2006,-,-,-,-,NaN
41,NOE_001,Noel Gallagher,EP,Rhapsody Originals,2006,-,-,-,-,NaN
42,GOR_006,Gorillaz,EP,(Dare) (EP Series),2006,-,-,-,-,NaN
43,GOR_007,Gorillaz,Live album,Demon Days: Live at the Manchester Opera House,2006,-,-,-,-,NaN
44,OAS_017,Oasis,Live album,Lord Don't Slow Me Down,2007,-,-,-,-,NaN
45,GOR_008,Gorillaz,EP,Feel Good Inc. (EP Series),2007,-,-,-,-,NaN
46,GOR_009,Gorillaz,Compilation,D-Sides,2007,63,1,10,2,NaN
47,OAS_018,Oasis,Album,Dig Out Your Soul,2008,1,33,5,5,2xPlatino
48,OAS_019,Oasis,Compilation,Greatest Hits,2008,-,-,-,-,NaN
49,OAS_020,Cookin' Soul/Jay-Z/Oasis,Remix mixtape album,OJAYZIS,2008,-,-,-,-,NaN
50,OAS_021,Oasis,EP,Boy With The Blues,2009,-,-,-,-,NaN
51,OAS_022,Oasis,Live EP,iTunes Festival: London 2009,2009,-,-,-,-,NaN
52,OAS_023,Oasis,Remix EP,Falling Down (A Monstrous Psychedelic Bubble E...,2009,-,-,-,-,NaN
53,NOE_002,Noel Gallagher,Live album,The Dreams We Have as Children,2009,1,3,-,-,NaN
54,BLU_017,Blur,Compilation,Midlife: A Begginers' Guide to Blur,2009,20,6,-,-,NaN
55,BLU_018,Blur,Live album,All the People: Blur Live at Hyde Park 02 July...,2009,70,1,-,-,NaN
56,BLU_019,Blur,Live album,All the People: Blur Live at Hyde Park 03 July...,2009,44,1,-,-,NaN
57,BLU_020,Blur,Live broadcast,2009-06-28: Glastonbury Festival of Contempora...,2009,-,-,-,-,NaN
58,OAS_024,Oasis,Compilation,Time Flies… 1994-2009,2010,1,680,131,1,8xPlatino
59,GOR_010,Gorillaz,Album,Plastic Beach,2010,2,31,2,35,Platino
60,GOR_011,Gorillaz,Album,The Fall,2010,12,3,24,4,NaN
61,GOR_012,Gorillaz,Live EP,iTunes Session,2010,-,-,154,1,NaN
62,BEA_001,Beady Eye,Live EP,iTunes Festival: London 2011,2011,-,-,-,-,NaN
63,BEA_002,Beady Eye,Album,Different Gear Still Speeding,2011,3,19,31,2,Oro
64,HFB_001,Noel Gallagher's High Flying Birds,Album,Noel Gallagher's High Flying Birds,2011,1,60,28,2,3xPlatino
65,GOR_013,Gorillaz,Compilation,The Singles Collection 2001-2011,2011,42,26,-,-,Platino
66,HFB_002,Noel Gallagher's High Flying Birds,Live album,International Magic Live at the O2,2012,-,-,-,-,NaN
67,HFB_003,Noel Gallagher's High Flying Birds,Compilation EP,Songs From the Great White North…,2012,-,-,-,-,NaN
68,BLU_021,Blur,Compilation,Blur 21: The Box,2012,71,1,-,-,NaN
69,BLU_022,Blur,Live album,Parklive,2012,91,1,-,-,NaN
70,BLU_023,Blur,Live EP,Live From the Brits,2012,-,-,-,-,NaN
71,GBQ_001,The Good the Bad & the Queen,Album,The Good the Bad & the Queen,2007,-,-,-,-,Oro
72,DAM_005,Damon Albarn,Album,Dr Dee,2012,42,1,-,-,NaN
73,BEA_003,Beady Eye,Album,BE,2013,2,8,-,-,Plata
74,BEA_004,Beady Eye,EP,42.42,2013,-,-,-,-,NaN
75,DAM_006,Michael Horovitz/Damon Albarn/Graham Coxon/Pau...,Album,Bankbusted Nuclear Detergent Blues,2013,-,-,-,-,NaN
76,OAS_025,Oasis,Demo album,Original 1993 Demos,2014,-,-,-,-,NaN
77,HFB_004,Noel Gallagher's High Flying Birds,Album,Chasing Yesterday,2014,1,44,24,2,Platino
78,DAM_007,Damon Albarn,Album,Everyday Robots,2014,2,9,-,-,Plata
79,DAM_008,Damon Albarn & The Heavy Seas,Live album,Live at the de de de der… (15 November 2014),2014,-,-,-,-,NaN
80,DAM_009,Damon Albarn & The Heavy Seas,Live album,Live at the de de de der… (16 November 2014),2014,-,-,-,-,NaN
81,HFB_005,Noel Gallagher's High Flying Birds,Remix album,Where the City Meets the Sky - Chasing Yerterd...,2015,35,1,-,-,NaN
82,BLU_024,Blur,Album,The Magic Whip,2015,1,14,12,2,Oro
83,HFB_006,Noel Gallagher's High Flying Birds,Album,Who Built the Moon?,2017,1,34,19,1,Platino
84,LIA_001,Liam Gallagher,Album,As You Were,2017,1,47,-,-,Platino
85,GOR_014,Gorillaz,Album,Humanz,2017,2,11,1,13,Oro
86,HFB_007,Noel Gallagher's High Flying Birds,Remix EP,It´s a Beautiful World (Remixes),2018,-,-,-,-,NaN
87,GOR_015,Gorillaz,Album,The Now Now,2018,5,5,3,14,Plata
88,LIA_002,Liam Gallagher,Album,Why Me? Why Not.,2019,1,28,-,-,Oro
89,HFB_008,Noel Gallagher's High Flying Birds,Remix EP,Wait and Return,2019,-,-,-,-,NaN
90,HFB_009,Noel Gallagher's High Flying Birds,EP,Black Star Dancing,2019,-,-,-,-,NaN
91,HFB_010,Noel Gallagher's High Flying Birds,EP,This Is the Place,2019,-,-,-,-,NaN
92,BLU_025,Blur,Live EP,Live at the BBC,2019,-,-,-,-,NaN
93,HFB_011,Noel Gallagher's High Flying Birds,EP,Blue Moon Rising,2020,-,-,-,-,NaN
94,LIA_003,Liam Gallagher,Live album,MTV Unplugged,2020,1,5,-,-,NaN
95,LIA_004,Liam Gallagher,EP,Acoustic Sessions,2020,24,2,-,-,NaN
96,GOR_016,Gorillaz,Album,Song Machine Season One: Strange Timez,2020,2,4,3,4,Plata
97,OAS_026,Oasis,Live album,Knebworth 1996,2021,4,8,-,-,Oro
98,HFB_012,Noel Gallagher's High Flying Birds,Compilation,Back the Way We Came: Vol. 1 (2011-2021),2021,1,11,-,-,Oro
99,BLU_026,Blur,Live album,BBC Radio 1 Broadcast John Peel Sessions 5th M...,2021,-,-,-,-,NaN
100,GOR_017,Gorillaz,Compilation,G Collection,2021,-,-,-,-,NaN
101,BLU_027,Blur,Live broadcast,1994-06-26: Glastonbury Festival of Contempora...,2021,-,-,-,-,NaN
102,GOR_018,Gorillaz,EP,Meanwhile EP,2021,-,-,-,-,NaN
103,DAM_010,Damon Albarn,Album,The Nearer the Fountain More Pure the Stream F...,2021,7,2,-,-,NaN
104,LIA_005,Liam Gallagher,Album,C'mon You Know,2022,1,5,-,-,Oro
105,LIA_006,Liam Gallagher,Live album,Down by the River Thames,2022,4,3,-,-,NaN
106,LIA_007,Liam Gallagher,EP,Diamond In The Dark,2022,-,-,-,-,NaN
107,DAM_011,Damon Albarn,Live EP,Live at The Photographers' Gallery (Amazon Mus...,2022,-,-,-,-,NaN
108,HFB_013,Noel Gallagher's High Flying Birds,Album,Council Skies,2023,2,8,20,1,Oro
109,LIAM_008,Liam Gallagher,Live album,Knebworth 22,2023,1,2,NaN,NaN,NaN
110,OAS_027,Oasis,Live album,Live at BBC Radio 1997,2023,-,-,-,-,NaN
111,GOR_019,Gorillaz,Album,Cracker Island,2023,1,4,1,12,Plata
112,BLU_028,Blur,Album,The Ballad of Darren,2023,1,5,8,3,Plata
113,BLU_029,Blur,Live album,Live in Sweden 1996,2023,-,-,-,-,NaN
114,LIA_009,Liam Gallagher/John Squire,Album,Liam Gallagher John Squire,2024,1,4,-,-,Plata
115,BLU_030,Blur,Live album,Live at Wembley Stadium,2024,6,1,-,-,NaN
116,DAM_012,Damon Albarn,EP,Pure Love,2024,-,-,-,-,NaN
117,OAS_0028,Oasis,Compilation,Complete Studio Album Collection,2025,-,-,-,-,NaN
118,GOR_020,Gorillaz,Live album,Demon Days: Live From the Apollo Theater,2025,91,1,25,1,NaN
119,GOR_021,Gorillaz,Album,The Mountain,2026,1,5,3,6,Plata

In [3]:
df.shape

(120, 10)

In [4]:
df.columns

Index(['album_id', 'artista_proyecto', 'tipo_discografia', 'nombre_album',
       'año_lanzamiento', 'UK_peak', 'semanas_chart_UK', 'US_peak',
       'semanas_chart_US', 'certificacion_BPI'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   album_id           120 non-null    object
 1   artista_proyecto   120 non-null    object
 2   tipo_discografia   120 non-null    object
 3   nombre_album       120 non-null    object
 4   año_lanzamiento    120 non-null    int64
 5   UK_peak            120 non-null    object
 6   semanas_chart_UK   119 non-null    object
 7   US_peak            119 non-null    object
 8   semanas_chart_US   119 non-null    object
 9   certificacion_BPI  46 non-null     object
dtypes: int64(1), object(9)
memory usage: 9.5+ KB

In [6]:
df["tipo_discografia"].head()

0             Album
1             Album
2             Album
3        Live album
4    Live broadcast
Name: tipo_discografia, dtype: object

In [7]:
df["año_lanzamiento"].head()

0    1991
1    1993
2    1994
3    1994
4    1994
Name: año_lanzamiento, dtype: int64

In [8]:
df["tipo_discografia"].value_counts()

tipo_discografia
Album                      42
Live album                 26
Compilation                15
EP                         15
Live EP                     6
Live broadcast              3
Remix EP                    3
Soundtrack album            2
Remix album                 2
Live remix album            1
Spokenword album            1
Remix mixtape album         1
Documentary compilation     1
Compilation EP              1
Demo album                  1
Name: count, dtype: int64

In [9]:
df["certificacion_BPI"].value_counts()

certificacion_BPI
Oro           12
Plata          9
Platino        8
3xPlatino      6
2xPlatino      2
8xPlatino      2
4xPlatino      2
10xPlatino     1
19xPlatino     1
7xPlatino      1
6xPlatino      1
5xPlatino      1
Name: count, dtype: int64

In [10]:
df["artista_proyecto"].value_counts()

artista_proyecto
Blur                                                        30
Oasis                                                       27
Gorillaz                                                    20
Noel Gallagher's High Flying Birds                          13
Liam Gallagher                                               8
Damon Albarn                                                 6
Beady Eye                                                    4
Damon Albarn & The Heavy Seas                                2
Noel Gallagher                                               2
Afel Bocoum /Damon Albarn/Toumani Diabaté/Ko Kan Ko Sata     1
Spacemonkeyz vs. Gorillaz                                    1
Damon Albarn & Michael Nyman                                 1
Damon Albarn & Einar Örn Benediktsson                        1
The Good the Bad & the Queen                                 1
Cookin' Soul/Jay-Z/Oasis                                     1
Michael Horovitz/Damon Albarn/Graham Coxon/Paul Weller       1
Liam Gallagher/John Squire                                   1
Name: count, dtype: int64

In [11]:
df.sort_values("año_lanzamiento", ascending=False).head(10)

,album_id,artista_proyecto,tipo_discografia,nombre_album,año_lanzamiento,UK_peak,semanas_chart_UK,US_peak,semanas_chart_US,certificacion_BPI
119,GOR_021,Gorillaz,Album,The Mountain,2026,1,5,3,6,Plata
117,OAS_0028,Oasis,Compilation,Complete Studio Album Collection,2025,-,-,-,-,NaN
118,GOR_020,Gorillaz,Live album,Demon Days: Live From the Apollo Theater,2025,91,1,25,1,NaN
115,BLU_030,Blur,Live album,Live at Wembley Stadium,2024,6,1,-,-,NaN
114,LIA_009,Liam Gallagher/John Squire,Album,Liam Gallagher John Squire,2024,1,4,-,-,Plata
116,DAM_012,Damon Albarn,EP,Pure Love,2024,-,-,-,-,NaN
110,OAS_027,Oasis,Live album,Live at BBC Radio 1997,2023,-,-,-,-,NaN
111,GOR_019,Gorillaz,Album,Cracker Island,2023,1,4,1,12,Plata
113,BLU_029,Blur,Live album,Live in Sweden 1996,2023,-,-,-,-,NaN
112,BLU_028,Blur,Album,The Ballad of Darren,2023,1,5,8,3,Plata

In [12]:
df.sort_values("año_lanzamiento", ascending=True).head(10)

,album_id,artista_proyecto,tipo_discografia,nombre_album,año_lanzamiento,UK_peak,semanas_chart_UK,US_peak,semanas_chart_US,certificacion_BPI
0,BLU_001,Blur,Album,Leisure,1991,7,22,-,-,Oro
1,BLU_002,Blur,Album,Modern Life Is Rubbish,1993,15,19,-,-,Oro
2,OAS_001,Oasis,Album,Definitely Maybe,1994,1,663,13,22,10xPlatino
3,OAS_002,Oasis,Live album,1994-04-24: Glastonbury Festival of Contempora...,1994,-,-,-,-,NaN
4,OAS_003,Oasis,Live broadcast,Oasis - Evening Session 1993,1994,-,-,-,-,NaN
5,BLU_003,Blur,Album,Parklife,1994,1,120,-,-,4xPlatino
6,BLU_004,Blur,Compilation,The Special Collectors Edition,1994,-,-,43,1,NaN
7,OAS_004,Oasis,Album,(What's the Story) Morning Glory?,1995,1,767,4,81,19xPlatino
8,OAS_005,Oasis,Live album,Live by the Sea,1995,-,-,-,-,3xPlatino
9,BLU_005,Blur,Album,The Great Escape,1995,1,56,150,1,3xPlatino

In [13]:
df[df["tipo_discografia"] == "Album"].head()

,album_id,artista_proyecto,tipo_discografia,nombre_album,año_lanzamiento,UK_peak,semanas_chart_UK,US_peak,semanas_chart_US,certificacion_BPI
0,BLU_001,Blur,Album,Leisure,1991,7,22,-,-,Oro
1,BLU_002,Blur,Album,Modern Life Is Rubbish,1993,15,19,-,-,Oro
2,OAS_001,Oasis,Album,Definitely Maybe,1994,1,663,13,22,10xPlatino
5,BLU_003,Blur,Album,Parklife,1994,1,120,-,-,4xPlatino
7,OAS_004,Oasis,Album,(What's the Story) Morning Glory?,1995,1,767,4,81,19xPlatino

In [14]:
df[df["artista_proyecto"] == "Blur"].head()

,album_id,artista_proyecto,tipo_discografia,nombre_album,año_lanzamiento,UK_peak,semanas_chart_UK,US_peak,semanas_chart_US,certificacion_BPI
0,BLU_001,Blur,Album,Leisure,1991,7,22,-,-,Oro
1,BLU_002,Blur,Album,Modern Life Is Rubbish,1993,15,19,-,-,Oro
5,BLU_003,Blur,Album,Parklife,1994,1,120,-,-,4xPlatino
6,BLU_004,Blur,Compilation,The Special Collectors Edition,1994,-,-,43,1,NaN
9,BLU_005,Blur,Album,The Great Escape,1995,1,56,150,1,3xPlatino

In [15]:
df.isna().sum().sort_values(ascending=False)

certificacion_BPI    74
semanas_chart_US      1
semanas_chart_UK      1
US_peak               1
artista_proyecto      0
album_id              0
UK_peak               0
año_lanzamiento       0
nombre_album          0
tipo_discografia      0
dtype: int64

In [16]:
df.groupby("tipo_discografia").size()

tipo_discografia
Album                      42
Compilation                15
Compilation EP              1
Demo album                  1
Documentary compilation     1
EP                         15
Live EP                     6
Live album                 26
Live broadcast              3
Live remix album            1
Remix EP                    3
Remix album                 2
Remix mixtape album         1
Soundtrack album            2
Spokenword album            1
dtype: int64

In [17]:
df.groupby("artista_proyecto").size()

artista_proyecto
Afel Bocoum /Damon Albarn/Toumani Diabaté/Ko Kan Ko Sata     1
Beady Eye                                                    4
Blur                                                        30
Cookin' Soul/Jay-Z/Oasis                                     1
Damon Albarn                                                 6
Damon Albarn & Einar Örn Benediktsson                        1
Damon Albarn & Michael Nyman                                 1
Damon Albarn & The Heavy Seas                                2
Gorillaz                                                    20
Liam Gallagher                                               8
Liam Gallagher/John Squire                                   1
Michael Horovitz/Damon Albarn/Graham Coxon/Paul Weller       1
Noel Gallagher                                               2
Noel Gallagher's High Flying Birds                          13
Oasis                                                       27
Spacemonkeyz vs. Gorillaz                                    1
The Good the Bad & the Queen                                 1
dtype: int64

In [18]:
df.groupby("artista_proyecto").size().reset_index(name="cantidad")

                                     artista_proyecto  cantidad
0   Afel Bocoum /Damon Albarn/Toumani Diabaté/Ko K...         1
1                                           Beady Eye         4
2                                                Blur        30
3                            Cookin' Soul/Jay-Z/Oasis         1
4                                        Damon Albarn         6
5               Damon Albarn & Einar Örn Benediktsson         1
6                        Damon Albarn & Michael Nyman         1
7                       Damon Albarn & The Heavy Seas         2
8                                            Gorillaz        20
9                                      Liam Gallagher         8
10                         Liam Gallagher/John Squire         1
11  Michael Horovitz/Damon Albarn/Graham Coxon/Pau...         1
12                                     Noel Gallagher         2
13                 Noel Gallagher's High Flying Birds        13
14                                              Oasis        27
15                          Spacemonkeyz vs. Gorillaz         1
16                       The Good the Bad & the Queen         1

In [19]:
df.groupby("tipo_discografia").size().reset_index(name="cantidad")

           tipo_discografia  cantidad
0                     Album        42
1               Compilation        15
2            Compilation EP         1
3                Demo album         1
4   Documentary compilation         1
5                        EP        15
6                   Live EP         6
7                Live album        26
8            Live broadcast         3
9          Live remix album         1
10                 Remix EP         3
11              Remix album         2
12      Remix mixtape album         1
13         Soundtrack album         2
14         Spokenword album         1

In [20]:
df.groupby("año_lanzamiento").size().reset_index(name="cantidad")

    año_lanzamiento  cantidad
0              1991         1
1              1993         1
2              1994         5
3              1995         3
4              1996         3
5              1997         4
6              1998         2
7              1999         3
8              2000         4
9              2001         4
10             2002         3
11             2003         2
12             2004         1
13             2005         3
14             2006         5
15             2007         4
16             2008         3
17             2009         8
18             2010         4
19             2011         4
20             2012         6
21             2013         3
22             2014         5
23             2015         2
24             2017         3
25             2018         2
26             2019         5
27             2020         4
28             2021         7
29             2022         4
30             2023         6
31             2024         3
32             2025         2
33             2026         1

In [21]:
por_tipo = (
    df.groupby("tipo_discografia")
      .size()
      .reset_index(name="cantidad")
      .sort_values("cantidad", ascending=False)
)

por_tipo

           tipo_discografia  cantidad
0                     Album        42
7                Live album        26
1               Compilation        15
5                        EP        15
6                   Live EP         6
8            Live broadcast         3
10                 Remix EP         3
13         Soundtrack album         2
11              Remix album         2
2            Compilation EP         1
4   Documentary compilation         1
3                Demo album         1
9          Live remix album         1
12      Remix mixtape album         1
14         Spokenword album         1

In [22]:
por_anio = (
    df.groupby("año_lanzamiento")
      .size()
      .reset_index(name="cantidad")
      .sort_values("cantidad", ascending=False)
)

por_anio.head(10)

    año_lanzamiento  cantidad
17             2009         8
28             2021         7
20             2012         6
30             2023         6
22             2014         5
2              1994         5
14             2006         5
26             2019         5
18             2010         4
19             2011         4

In [23]:
por_certificacion = (
    df.groupby("certificacion_BPI")
      .size()
      .reset_index(name="cantidad")
      .sort_values("cantidad", ascending=False)
)

por_certificacion.head(10)

   certificacion_BPI  cantidad
9                Oro        12
10             Plata         9
11           Platino         8
3          3xPlatino         6
8          8xPlatino         2
4          4xPlatino         2
2          2xPlatino         2
1         19xPlatino         1
0         10xPlatino         1
7          7xPlatino         1

In [24]:
# save

por_tipo.to_csv("por_tipo.csv", index=False)
por_anio.to_csv("por_anio.csv", index=False)
por_certificacion.to_csv("por_certificacion.csv", index=False)

In [25]:
alt.Chart(por_tipo).mark_bar().encode(
    x=alt.X("tipo_discografia:N", title="Tipo de discografía"),
    y=alt.Y("cantidad:Q", title="Cantidad"),
    tooltip=["tipo_discografia", "cantidad"]
).properties(
    title="Discografía"
)

alt.Chart(...)

In [26]:
por_anio_ordenado = (
    df.groupby("año_lanzamiento")
      .size()
      .reset_index(name="cantidad")
      .sort_values("año_lanzamiento")
)

por_anio_ordenado.head()

   año_lanzamiento  cantidad
0             1991         1
1             1993         1
2             1994         5
3             1995         3
4             1996         3

In [27]:
alt.Chart(por_anio_ordenado).mark_line(point=True).encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    tooltip=["año_lanzamiento", "cantidad"]
).properties(
    title="Cantidad de discos por año"
)

alt.Chart(...)

In [28]:

# Filtrar por banda
bandas = df[df["artista_proyecto"].isin(["Blur", "Oasis"])]

# Contar discos
evolucion = (
    bandas.groupby(["artista_proyecto", "año_lanzamiento"])
    .size()
    .reset_index(name="cantidad")
)

# Crear gráfico de líneas
grafico_9 = alt.Chart(evolucion).mark_line(point=True).encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    tooltip=["artista_proyecto", "año_lanzamiento", "cantidad"]
).properties(
    title="Cantidad de discos por año por banda"
).interactive()

grafico_9

alt.Chart(...)

In [29]:
# Filtrar por banda
bandas = df[df["artista_proyecto"].isin(["Blur", "Oasis", "Gorillaz", "Noel Gallagher's High Flying Birds"])]

# Contar discos
evolucion = (
    bandas.groupby(["artista_proyecto", "año_lanzamiento"])
    .size()
    .reset_index(name="cantidad")
)

# Crear gráfico de líneas
grafico_3 = alt.Chart(evolucion).mark_line(point=True).encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    tooltip=["artista_proyecto", "año_lanzamiento", "cantidad"]
).properties(
    title="Cantidad de discos por año por banda"
).interactive()

grafico_3

alt.Chart(...)

In [30]:
# guardar
grafico_3.save("cantidad_discos_año_banda.html")

In [31]:
# Filtrar por banda
bandas = df[df["artista_proyecto"].isin(["Blur", "Oasis", "Gorillaz", "Noel Gallagher's High Flying Birds", "Noel Gallagher", "Liam Gallagher", "Damon Albarn", "Beady Eye"])]

# Contar discos
evolucion = (
    bandas.groupby(["artista_proyecto", "año_lanzamiento"])
    .size()
    .reset_index(name="cantidad")
)

# Crear gráfico de líneas
grafico_4 = alt.Chart(evolucion).mark_line(point=True).encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    tooltip=["artista_proyecto", "año_lanzamiento", "cantidad"]
).properties(
    title="Cantidad de discos por año por banda"
).interactive()

grafico_4

alt.Chart(...)

In [32]:
# guardar
grafico_4.save("cantidad_discos_año_banda_2.html")

In [33]:
# Filtrar por banda
datos = df[df["artista_proyecto"].isin(["Blur", "Oasis", "Gorillaz", "Noel Gallagher's High Flying Birds", "Beady Eye", "Liam Gallagher", "Noel Gallagher"])]

# Contar la cantidad de discos por banda
conteo = (
    datos.groupby(["artista_proyecto", "tipo_discografia"])
    .size()
    .reset_index(name="cantidad")
)

# Crear el gráfico
grafico_5 = alt.Chart(conteo).mark_bar().encode(
    x=alt.X("tipo_discografia:N", title="Tipo de disco lanzado"),
    y=alt.Y("cantidad:Q", title="Número de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    xOffset="artista_proyecto:N",
    tooltip=["artista_proyecto", "tipo_discografia", "cantidad"]
).properties(
    title="Discografía: Albarn vs. los Gallagher",
    width=1000,
    height=350
)

grafico_5

alt.Chart(...)

In [34]:
# guardar
grafico_5.save("discografia_albarn_gallagher.html")

In [35]:
# Filtrar por banda
datos = df[df["artista_proyecto"].isin(["Blur", "Oasis", "Gorillaz", "Noel Gallagher's High Flying Birds"])]

# Contar la cantidad de discos por banda
conteo = (
    datos.groupby(["artista_proyecto", "tipo_discografia"])
    .size()
    .reset_index(name="cantidad")
)

# Crear el gráfico
grafico = alt.Chart(conteo).mark_bar().encode(
    x=alt.X("tipo_discografia:N", title="Tipo de disco lanzado"),
    y=alt.Y("cantidad:Q", title="Número de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    xOffset="artista_proyecto:N",
    tooltip=["artista_proyecto", "tipo_discografia", "cantidad"]
).properties(
    title="Blur vs. Oasis: carrera musical",
    width=700,
    height=350
)

grafico

alt.Chart(...)

Damon Albarn gana en **los cuatro tipos discográficos más importantes de la industria** (Album, Live Album, EP, Live EP), teniendo únicamente en cuenta los proyectos "Blur" y "Gorillaz".

In [36]:
# Filtrar por tipo de discografía
discos = df[df["tipo_discografia"].isin(["Album", "Compilation", "EP", "Live album", "Live EP"])]

# Contar la cantidad de discos por banda
conteo = (
    discos.groupby(["artista_proyecto", "tipo_discografia"])
    .size()
    .reset_index(name="cantidad")
)

# Crear el gráfico
grafico_7 = alt.Chart(conteo).mark_bar().encode(
    x=alt.X("tipo_discografia:N", title="Tipo de disco lanzado"),
    y=alt.Y("cantidad:Q", title="Número de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    xOffset="artista_proyecto:N",
    tooltip=["artista_proyecto", "tipo_discografia", "cantidad"]
).properties(
    title="Blur vs. Oasis: carrera musical",
    width=1000,
    height=350
).interactive()

grafico_7

alt.Chart(...)

In [37]:
# 1. Define la lista exacta de las bandas que quieres incluir en el gráfico
bandas_a_mostrar = ["Blur", "Oasis", "Gorillaz", "Noel Gallagher's High Flying Birds"] # Añade o quita bandas aquí

# 2. Filtrar el DataFrame original por tipo de discografía Y por la lista de bandas
discos = df[
    df["tipo_discografia"].isin(["Album", "Compilation", "EP", "Live album", "Live EP"]) &
    df["artista_proyecto"].isin(bandas_a_mostrar)
]

# 3. Contar la cantidad de discos por banda
conteo = (
    discos.groupby(["artista_proyecto", "tipo_discografia"])
    .size()
    .reset_index(name="cantidad")
)

# 4. Crear el gráfico con los datos ya filtrados
grafico_6 = alt.Chart(conteo).mark_bar().encode(
    x=alt.X("tipo_discografia:N", title="Tipo de disco lanzado"),
    y=alt.Y("cantidad:Q", title="Número de discos"),
    color=alt.Color("artista_proyecto:N", title="Banda"),
    xOffset="artista_proyecto:N",
    tooltip=["artista_proyecto", "tipo_discografia", "cantidad"]
).properties(
    title="Blur vs. Oasis: carrera musical",
    width=1000,
    height=350
).interactive()

grafico_6

alt.Chart(...)

In [38]:
top_anios = (
    df.groupby("año_lanzamiento")
      .size()
      .reset_index(name="cantidad")
      .sort_values("cantidad", ascending=False)
      .head(10)
)

top_anios

    año_lanzamiento  cantidad
17             2009         8
28             2021         7
20             2012         6
30             2023         6
22             2014         5
2              1994         5
14             2006         5
26             2019         5
18             2010         4
19             2011         4

In [39]:
grafico_2 = alt.Chart(top_anios).mark_bar().encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad"),
    tooltip=["año_lanzamiento", "cantidad"]
).properties(
    title="Top 10 años con más discos en la base"
)

grafico_2

alt.Chart(...)

In [40]:
# guardar
grafico_2.save("top_anios.html")

In [41]:
import altair as alt

# 1. Define los nombres exactos que aparecen en tu columna "artista_proyecto"
nombres_bandas = ["Beady Eye", "Blur", "Damon Albarn", "Gorillaz", "Liam Gallagher", "Noel Gallagher", "Noel Gallagher's High Flying Birds", "Oasis", "The Good the Bad & the Queen"]

# 2. Define los colores que quieres para cada banda (en el mismo orden)
colores_personalizados = ["#6D8FAD", "#FFCC00", "#997A00", "#FF7F00", "#2A86D6", "#185182", "#3A6A93", "#006ECE", "#FDE92B"]

chart = alt.Chart(evolucion).mark_line(
    point=alt.OverlayMarkDef(filled=False, fill="white")
).encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    color=alt.Color(
        "artista_proyecto:N",
        title="Banda",
        # 3. Agrega la escala de colores aquí
        scale=alt.Scale(domain=nombres_bandas, range=colores_personalizados)
    ),
    tooltip=["artista_proyecto", "año_lanzamiento", "cantidad"]
).properties(
    title="Cantidad de discos por año por banda"
).interactive()

chart

alt.Chart(...)

In [42]:
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'x': [1, 3, 5, 7, 9],
    'y': [1, 3, 5, 7, 9],
    'label': ['A', 'B', 'C', 'D', 'E']
})

# 1. Define los nombres exactos que aparecen en tu columna "artista_proyecto"
nombres_bandas = ["Beady Eye", "Blur", "Damon Albarn", "Gorillaz", "Liam Gallagher", "Noel Gallagher", "Noel Gallagher's High Flying Birds", "Oasis", "The Good the Bad & the Queen"]

# 2. Define los colores que quieres para cada banda (en el mismo orden)
colores_personalizados = ["#6D8FAD", "#FFCC00", "#997A00", "#FF7F00", "#2A86D6", "#185182", "#3A6A93", "#006ECE", "#FDE92B"]

point_chart = alt.Chart(evolucion).mark_point().encode(
    x=alt.X("año_lanzamiento:O", title="Año"),
    y=alt.Y("cantidad:Q", title="Cantidad de discos"),
    color=alt.Color(
        "artista_proyecto:N",
        title="Banda",
        # 3. Agrega la escala de colores aquí
        scale=alt.Scale(domain=nombres_bandas, range=colores_personalizados)
    ),
    tooltip=["artista_proyecto", "año_lanzamiento", "cantidad"]
).properties(
    title="Damon Albarn vs. los Gallagher: Vigencia discográfica a lo largo de los años"
)


# Llamamos a la variable para renderizar solo los puntos
point_chart

alt.Chart(...)